name: Deploy wasm version to Pages

on:
  workflow_dispatch:
  
env:
  PROJECT_PATH: ./BugFablesSaveEditor/BugFablesSaveEditor.Browser

jobs:
  build:  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        working-directory: ${{ env.PROJECT_PATH }}
        run: dotnet restore
      - name: Build
        working-directory: ${{ env.PROJECT_PATH }}
        run: dotnet build --no-restore
      - name: Test
        working-directory: ${{ env.PROJECT_PATH }}
        run: dotnet test --no-build
      - name: Publish
        working-directory: ${{ env.PROJECT_PATH }}
        run: dotnet publish -c Release
      - name: Prepare AppBundle Directory
        working-directory: ${{ env.PROJECT_PATH }}/bin/Release/AppBundle
        run: rm *.map  
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{ env.PROJECT_PATH }}/bin/Release/AppBundle

#  deploy:
#    needs: build
#    concurrency:
#      group: "pages"
#      cancel-in-progress: false
#    permissions:
#      pages: write      
#      id-token: write 
#    environment:
#      name: github-pages
#      url: ${{ steps.deployment.outputs.page_url }}
#    runs-on: ubuntu-latest
#    steps:
#      - name: Setup Pages
#        uses: actions/configure-pages@v3
#      - name: Deploy to GitHub Pages
#        id: deployment
#        uses: actions/deploy-pages@v2
